// Generated by CoffeeScript 1.3.3
var hygiene, social;

hygiene = {
  pageheader: "Self-Care",
  questions: [
    {
      question: "When was your last shower?",
      choicetype: "radio",
      answers: ["Today", "Yesterday", "Two days ago", "I don't know"]
    }, {
      question: "When was the last time you brushed your teeth?",
      choicetype: "radio",
      answers: ["Today", "Yesterday", "Two days ago", "I don't know"]
    }, {
      question: "When was the last time you pooped?",
      choicetype: "radio",
      answers: ["Today", "Yesterday", "Two days ago", "I don't know"]
    }, {
      question: "How much do you weigh today?",
      choicetype: "keypad"
    }, {
      question: "Do you take any medications?",
      choicetype: "radio",
      answers: ["Yes", "No"]
    }, {
      question: "Did you take them the last time you were supposed to??",
      choicetype: "radio",
      answers: ["Yes", "No"]
    }
  ]
};

social = {
  pageheader: "Safety and Security",
  questions: [
    {
      question: "Is anyone teasing you?",
      choicetype: "radio",
      answers: ["Yes", "No"]
    }, {
      question: "Is anyone bullying you?",
      choicetype: "radio",
      answers: ["Yes", "No"]
    }, {
      question: "Is anyone touching you or making you touch them?",
      choicetype: "radio",
      answers: ["Yes", "No"]
    }, {
      question: "Has anyone asked you to keep a secret?",
      choicetype: "radio",
      answers: ["Yes", "No"]
    }, {
      question: "Do you take any medications?",
      choicetype: "radio",
      answers: ["Yes", "No"]
    }, {
      question: "Did you take them the last time you were supposed to??",
      choicetype: "radio",
      answers: ["Yes", "No"]
    }
  ]
};
